name: Build and Push

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'docker-compose.yml'
      - 'Dockerfile.dev'

env:
  PROJECT_ID: gloo-hackathon-472520
  GAR_LOCATION: us-central1
  REPOSITORY: fastapi-cms-dev
  SERVICE: fastapi-cms

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v3'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v3'

    - name: Configure Docker to use gcloud as credential helper
      run: |-
        gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}
        tags: |
          type=sha,prefix=main-
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Output image details
      run: |-
        echo "✅ Docker image built and pushed successfully!"
        echo "📦 Image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
        echo "🏷️  Tags: latest, main-${{ github.sha }}"
        echo ""
        echo "🚀 Next: Deploy this image using your Pulumi infrastructure repo"